# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, these are LLM Tools Go tasks!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  installtools:
    cmds:
      # Install task, go, golangci-lint, cloc externally. E.g via asdf. the needed versions are pinned in .tool-versions file.
      - go install golang.org/x/tools/gopls@v0.21.1
      - go install github.com/oligot/go-mod-upgrade@v0.12.0
      - go install github.com/kisielk/godepgraph@v1.0.0
      - go install github.com/ppipada/refdir@v0.7.0
      - go install github.com/vladopajic/go-test-coverage/v2@v2.18.3

  cloc:
    cmds:
      - |
        cloc --vcs=git --ignored=ignored.txt \
             --force-lang=Mustache,tmpl --force-lang=INI,env --force-lang=INI,dev --force-lang=INI,prod \
             --exclude_ext=yaml,sum,mod,md5 --not-match-f='LICENSE$|\.gitignore$' \
             .

  godepgraph:
    cmds:
      - godepgraph -s -o github.com/flexigpt/llmtools-go,command-line-arguments registry.go | dot -Tpng -o godepgraph.png

  tagstats:
    cmds:
      - ./scripts/git_tag_stats.sh

  lint-gopls:
    cmds:
      - ./scripts/lint_gopls_check.sh

  lint-godotfix:
    cmds:
      - golangci-lint run --fix --enable-only=godot

  lint-gosort:
    cmds:
      - refdir ./...

  lint:
    cmds:
      - golangci-lint run ./... -v

  test:
    cmds:
      # The count=1 is needed to disable test caching. this is so that coverage doesnt show stale data.
      # Issue: https://github.com/golang/go/issues/74873
      - go test -count=1 -covermode=atomic -coverpkg=./... -coverprofile=coverage.out -tags=integration ./...
      - go tool cover -func=coverage.out
      - go-test-coverage --config=./.testcoverage.yml

  lt:
    cmds:
      - task: lint
      - task: test
